### ISSUE TITLE
佬，好像无法在租的云服务器上使用

### ISSUE THREAD

**Issue by 1zhangyy1** [AIFSH/MiniMates-ComfyUI#1]
/root/miniconda3/bin/python /root/autodl-tmp/ComfyUI/custom_nodes/MiniMates-ComfyUI/minimates/interface/interface_audio.py /root/autodl-tmp/ComfyUI/custom_nodes/MiniMates-ComfyUI/temp/tmpie_3n4c0.png /root/autodl-tmp/ComfyUI/custom_nodes/MiniMates-ComfyUI/temp/tmpfllinwlo.wav /root/autodl-tmp/ComfyUI/output/tmpie_3n4c0_tmpfllinwlo.mp4
/root/miniconda3/lib/python3.10/site-packages/glfw/__init__.py:914: GLFWError: (65544) b'X11: The DISPLAY environment variable is missing'
warnings.warn(message, GLFWError)
Traceback (most recent call last):
File "/root/autodl-tmp/ComfyUI/custom_nodes/MiniMates-ComfyUI/minimates/interface/interface_audio.py", line 19, in <module>
from interface.utils import rotate,face_interface,face_process,audio_interface,eularAngle2Matrix,generate_bg_mask
File "/root/autodl-tmp/ComfyUI/custom_nodes/MiniMates-ComfyUI/minimates/interface/../interface/utils.py", line 12, in <module>
from train.data.dataset_faceReenactment3 import crop_,get_image,adjust_verts,get_standard_image
File "/root/autodl-tmp/ComfyUI/custom_nodes/MiniMates-ComfyUI/minimates/interface/../train/data/dataset_faceReenactment3.py", line 9, in <module>
from obj_utils.opengl_texture_render import render2cv,set_ref_texture
File "/root/autodl-tmp/ComfyUI/custom_nodes/MiniMates-ComfyUI/minimates/interface/../obj_utils/opengl_texture_render.py", line 66, in <module>
raise Exception("glfw can not be initialized!")
Exception: glfw can not be initialized!

**Comment by AIFSH** [comment]
是的，需要有显示器才能渲染
